# -*- coding: utf-8 -*-
"""plot_growth.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_zOcy8s7sWPADM-xwpzBhSJZC_kngE8i
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# 1. Load the data
# Make sure 'Bacterial_growth_.csv' is in the same directory as this script,
# or provide the full path to the file.
growth_data = pd.read_csv("Bacterial_growth_.csv")

# Check if data loaded correctly (optional)
# print(growth_data.head())

# 2. Create the plot
# We want to plot OD600 vs. Time_Hours, with different lines/colors for each Strain.

plt.figure(figsize=(8, 6)) # Set the figure size

# Use seaborn for a nice line plot
sns.lineplot(data=growth_data, x="Time_Hours", y="OD600", hue="Strain", marker="o", linewidth=2, markersize=8)

plt.title("Bacterial Growth Over Time", fontsize=16)
plt.xlabel("Time (Hours)", fontsize=12)
plt.ylabel("Optical Density (OD600)", fontsize=12)
plt.legend(title="Bacterial Strain", loc="upper left")
plt.grid(True, linestyle='--', alpha=0.7) # Add a light grid
sns.despine() # Remove top and right spines for a cleaner look

# Display the plot (optional, will show in a new window)
# plt.show()

# 3. Save the plot
# This will save the plot as a PNG file in the same directory.
plt.savefig("bacterial_growth_plot.png", dpi=300, bbox_inches='tight')

print("Plot saved as bacterial_growth_plot.png")